name: Build_And_Test

on:
  push:
    branches: [ dev, main, 'feat/**' ]
  pull_request:
    branches: [ dev, main ]

jobs:

  linux:    
    name: build on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x 
    
    - name: Setup .NET SDK 5.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x 

    - name: Setup .NET SDK 3.1.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x 

    - name: Show dotnet Version
      run: |
        dotnet --list-sdks
        dotnet --list-runtimes

    - name: Build with dotnet      
      run: |
        dotnet build src/Dtmcli/Dtmcli.csproj 

    - name: Run tests on netcoreapp3.1
      run: |
        dotnet test --framework=netcoreapp3.1 src/Dtmcli.Tests/Dtmcli.Tests.csproj

    - name: Run tests on net5.0
      run: |
        dotnet test --framework=net5.0 src/Dtmcli.Tests/Dtmcli.Tests.csproj

    - name: Run tests on net6.0
      run: |
        dotnet test --framework=net6.0 src/Dtmcli.Tests/Dtmcli.Tests.csproj --collect:"XPlat Code Coverage"

    - name: Prepare Codecov
      run: |
        mkdir ${{ github.workspace }}/coverage/

        cp ${{ github.workspace }}/src/Dtmcli.Tests/TestResults/*/coverage.cobertura.xml  ${{ github.workspace }}/coverage/

        ls ${{ github.workspace }}/coverage/

    - name: Upload coverage to Codecov
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: ${{ github.workspace }}/coverage/coverage.cobertura.xml
        name: codecov-umbrella
        verbose: true    